### PR TITLE
Update dependencies and warning cleanup for newer elixir versions

### PR DESCRIPTION
**Pull request by d-mart**
* `HTTPoison` was pinned to an old version that is pinned to a deprecated version of `hackney` (~ `1.6`) 
* `Poison` has had a major-version release; it now returns a 3-tuple error in certain cases.  The `case` around this call has been bolstered to handle the additional format:

```elixir
iex(1)> Poison.Parser.parse("")
{:error, :invalid, 0}  # <-- new, previously: {:error, :invalid}

iex(2)> Poison.Parser.parse("c")
{:error, {:invalid, "c", 0}} # <-- existing parse error format still tolerated
```
* Add OTP 20 to the build matrix, but only for elixir 1.4
* CI tests run against poison `2.x` and `3.x`

### CODE REVIEW

**Comment by d-mart** [comment]
Seems phoenix won't accept a `3.x` Poison, and there is probably a large overlap in user-base (certainly there is for *my* use case 😜 ).  I will probably split this PR and hold off on the `Poison` parts.

**Comment by pezra** [comment]
Any way we could support poison 2.x and 3.x?

**Comment by d-mart** [comment]
Yes.  It also looks like phoenix has that very dep version description coming in `1.3.0-rcX`.

**Comment by pezra** [comment]
All the `()` turds make me 😢.

**Comment by pezra** [comment]
Can we get a Travis build with the old and new versions of poison to make sure we don't break compatibility going forward.

**Comment by d-mart** [comment]
Sure! I can also pull the `()` commit, but seems to be the way things are going, and the warning spam could hide more legit problems.

**Comment by pezra** [comment]
Don't pull that commit. I am sad that elixir is going to require parens but
that doesn't change anything.

**Comment by d-mart** [comment]
I added some code in `mix.exs` to look for patterned environment variables to force deps (i.e. `:poison`) versions.  I did this instead of having different `mix-$WHATEVER.exs` files so that there is still Just One™ list of deps to edit.  This way, for most use cases, the fact that Travis can test multiple dep versions is hidden (other than some extra `defp ...` at the bottom of the file).

**Comment by d-mart** [comment]
I force-pushed a small change and it seems to have slipped thru Travis's fingers.  Closing and re-opening to force a rebuild.  _brb_

**Comment by glassbead0** [comment]
any more changes needed for this PR?

**Comment by pezra** [comment]
released as 5.3

**Pull request merged**
