### PR TITLE
Loosen httpoison version restriction

### PR DESCRIPTION
**Pull request by adherr**
This makes dependency resolution in my project easier.

### CODE REVIEW

**Comment by adherr** [comment]
Should I upgrade it in the lock file?

**Comment by adherr** [comment]
I'd like to bump to httpoison "~>1.0", but that seems like a breaking change for dependency resolution, even though there are [no breaking changes in httpoison 1.0](https://github.com/edgurgel/httpoison/issues/225)

**Comment by pezra** [comment]
since you'd like to include httpoison 1.0 maybe change the [version requirements to `"~> 0.11 or ~> =1.0"`](https://hexdocs.pm/elixir/Version.html#module-requirements)? Please do bump the lock file to make sure the new versions still work correctly.

**Comment by adherr** [comment]
I added a newer version to the lock file, but it's 0.13.0 rather than 1.1.1. Not sure how to get mix to choose the other branch of that `or`. It does resolve to httpoison 1.1.1 in my project though.

**Comment by pezra** [comment]
maybe `"~> 1.0 or ~> 0.11"` as the requirement?

**Comment by pezra** [comment]
released as 7.1.0

**Pull request merged**
